import type { RouteName } from "./routes"

export const images = {
	"favicon": "/favicon.png",
	"home.hero": "/images/01.webp",
	"home.feature": "/images/16.webp",
	"fiber.hero": "/images/08.webp",
	"fiber.material": "/images/07.webp",
	"fiber.heritage": "/images/11.webp",
	"fiber.origin": "/images/04.webp",
	"organization.hero": "/images/02.webp",
	"organization.conservation": "/images/09.webp",
	"contact.hero": "/images/05.webp",
	"contact.availability": "/images/06.webp",
	"contact.closing": "/images/10.webp",
} as const

const es = {
	"navigation.home": "Inicio",
	"navigation.fiber": "Fibra de vicuña",
	"navigation.organization": "ANMVB",
	"navigation.contact": "Contacto",
	"common.languageLabel": "Idioma",
	"common.imageAlt": "Vicuña en un paisaje altoandino",
	"footer.title": "Fibra boliviana. Origen comunitario.",
	"footer.text": "Asociación Nacional de Manejadores de Vicuña de Bolivia",
	"footer.rights": "© 2026 ANMVB. Todos los derechos reservados. Las fotografías no pueden reproducirse ni utilizarse sin autorización escrita previa.",
	"home.pageTitle": "Inicio",
	"home.hero.eyebrow": "Fibra de origen boliviano",
	"home.hero.title": "La fibra más fina de los Andes, manejada por sus comunidades.",
	"home.hero.body": "ANMVB reúne a comunidades que conservan la vicuña y comercializan su fibra de manera organizada.",
	"home.hero.primaryAction": "Conocer la fibra",
	"home.hero.secondaryAction": "Contacto comercial",
	"home.intro.eyebrow": "Origen y propósito",
	"home.intro.title": "Una cadena de valor que nace en el territorio",
	"home.intro.body": "Conservación, manejo comunitario y calidad, pensados para compradores que valoran un origen responsable.",
	"home.values.1.title": "Procedencia clara",
	"home.values.1.body": "Fibra vinculada a comunidades y territorios productores.",
	"home.values.2.title": "Manejo responsable",
	"home.values.2.body": "Un aprovechamiento que respeta la conservación de la vicuña.",
	"home.values.3.title": "Trato directo",
	"home.values.3.body": "Un proceso comercial basado en el diálogo y en acuerdos claros.",
	"home.feature.eyebrow": "Fibra de vicuña",
	"home.feature.title": "Calidad natural, identidad altoandina",
	"home.feature.body": "Una materia prima excepcional para compradores especializados y cadenas textiles de alto valor.",
	"home.feature.action": "Ver características",
	"home.closing.title": "Hablemos de disponibilidad y oportunidades comerciales.",
	"home.closing.body": "Cada operación comienza con una conversación directa con ANMVB.",
	"home.closing.action": "Iniciar contacto",
	"fiber.pageTitle": "Fibra de Vicuña",
	"fiber.hero.eyebrow": "Fibra de vicuña",
	"fiber.hero.title": "Una fibra excepcional, desde su origen",
	"fiber.hero.body": "Calidad, origen y disponibilidad de la fibra de vicuña: lo que necesita saber antes de contactarnos.",
	"fiber.material.eyebrow": "Materia prima",
	"fiber.material.title": "Lo que la hace única",
	"fiber.material.body": "La fibra de vicuña se distingue por su finura, ligereza y suavidad, además de un tacto y una calidez poco comunes en otras fibras naturales. Estas propiedades explican por qué ha sido, históricamente, una de las fibras más cotizadas del mundo.",
	"fiber.heritage.eyebrow": "Herencia andina",
	"fiber.heritage.title": "Un manejo con raíces antiguas",
	"fiber.heritage.body": "El arreo, la captura y la esquila de la vicuña no son técnicas nuevas: culturas prehispánicas de los Andes ya las practicaban, siglos atrás. El sistema de manejo sostenible que hoy siguen las comunidades bolivianas tiene poco más de 25 años, pero se apoya en ese conocimiento heredado.",
	"fiber.origin.eyebrow": "Procedencia",
	"fiber.origin.title": "Origen y trazabilidad",
	"fiber.origin.body": "La fibra proviene de vicuñas manejadas por comunidades bolivianas. En cada operación buscamos mantener clara esa relación entre el producto, la comunidad que participa en su manejo y el territorio del que procede.",
	"fiber.sales.eyebrow": "Comercialización",
	"fiber.sales.title": "Disponibilidad y proceso de venta",
	"fiber.sales.body": "Los volúmenes disponibles dependen de la producción de cada temporada. ANMVB atiende cada consulta de forma directa, para conversar sobre disponibilidad, precio, documentación, entrega y demás condiciones comerciales.",
	"fiber.closing.title": "Consulte por fibra disponible",
	"fiber.closing.body": "Escríbanos con su requerimiento y le respondemos con los detalles.",
	"fiber.closing.action": "Contactar a ANMVB",
	"organization.pageTitle": "Asociación",
	"organization.hero.eyebrow": "La asociación",
	"organization.hero.title": "Comunidades organizadas alrededor de la vicuña",
	"organization.hero.body": "Una representación nacional para fortalecer el manejo, la conservación y la comercialización de la fibra.",
	"organization.identity.eyebrow": "Identidad",
	"organization.identity.title": "Quiénes somos",
	"organization.identity.body": "ANMVB reúne a comunidades y organizaciones dedicadas al manejo de la vicuña en Bolivia. La asociación representa sus intereses y fortalece su participación en la cadena de valor de la fibra.",
	"organization.purpose.eyebrow": "Dirección",
	"organization.purpose.title": "Nuestro propósito",
	"organization.purpose.body": "Buscamos que el aprovechamiento responsable de la vicuña abra mejores oportunidades para las comunidades, a través de coordinación, representación y una comercialización organizada.",
	"organization.conservation.eyebrow": "Compromiso",
	"organization.conservation.title": "Manejo y conservación",
	"organization.conservation.body": "El manejo comunitario une el aprovechamiento de la fibra con el cuidado de la especie y su hábitat. La conservación es la base que sostiene esta actividad y su valor para las comunidades a lo largo del tiempo.",
	"organization.closing.title": "Conozca una organización con origen comunitario",
	"organization.closing.body": "ANMVB combina experiencia territorial y proyección comercial.",
	"organization.closing.action": "Hablar con la asociación",
	"contact.pageTitle": "Contacto Comercial",
	"contact.hero.eyebrow": "Contacto comercial",
	"contact.hero.title": "Hablemos de fibra de vicuña boliviana",
	"contact.hero.body": "Atendemos a compradores interesados en conocer la disponibilidad, los volúmenes y las condiciones de comercialización de la fibra que producen nuestras comunidades asociadas.",
	"contact.hero.action": "Hacer una consulta",
	"contact.hero.imageAlt": "Fibra de vicuña boliviana agrupada",
	"contact.requirements.eyebrow": "Qué necesitamos saber",
	"contact.requirements.title": "Cuéntenos qué está buscando",
	"contact.requirements.body": "Para darle una respuesta concreta, cuéntenos qué tipo de comprador o empresa es, para qué usará la fibra, el volumen aproximado que necesita y el país de destino.",
	"contact.requirements.1": "Comprador",
	"contact.requirements.2": "Uso",
	"contact.requirements.3": "Volumen",
	"contact.requirements.4": "Destino",
	"contact.availability.eyebrow": "Disponibilidad",
	"contact.availability.title": "Oferta disponible según temporada y producción",
	"contact.availability.body": "ANMVB reúne la oferta de fibra de sus comunidades asociadas. La disponibilidad y los volúmenes varían según la temporada, por lo que revisamos cada requerimiento de acuerdo con la producción disponible al momento de la consulta.",
	"contact.availability.imageAlt": "Persona trabajando con fibra de vicuña",
	"contact.process.eyebrow": "Cómo se concreta una compra",
	"contact.process.1.title": "Consulta",
	"contact.process.1.body": "Nos cuenta qué está buscando y las características de la compra.",
	"contact.process.2.title": "Propuesta",
	"contact.process.2.body": "Confirmamos disponibilidad y conversamos sobre volumen, precio y condiciones aplicables.",
	"contact.process.3.title": "Acuerdo",
	"contact.process.3.body": "Definimos juntos la documentación, la entrega y el resto de las condiciones comerciales.",
	"contact.closing.title": "Relación directa, origen comunitario",
	"contact.closing.body": "Si busca fibra de vicuña con respaldo de origen, escríbanos y conversamos sobre la oferta disponible.",
	"contact.closing.action": "Contactar a ANMVB",
	"contact.closing.imageAlt": "Vicuñas junto a sus manejadores comunitarios",
} as const

const en = {
	"navigation.home": "Home",
	"navigation.fiber": "Vicuña fiber",
	"navigation.organization": "ANMVB",
	"navigation.contact": "Contact",
	"common.languageLabel": "Language",
	"common.imageAlt": "Vicuña in a high-Andean landscape",
	"footer.title": "Bolivian fiber, rooted in community.",
	"footer.text": "National Association of Vicuña Management Communities of Bolivia",
	"footer.rights": "© 2026 ANMVB. All rights reserved. Photographs may not be reproduced or used without prior written permission.",
	"home.pageTitle": "Home",
	"home.hero.eyebrow": "Fiber of Bolivian origin",
	"home.hero.title": "The finest fiber in the Andes, managed by its communities.",
	"home.hero.body": "ANMVB brings together communities that conserve vicuña and market its fiber through an organized process.",
	"home.hero.primaryAction": "Discover the fiber",
	"home.hero.secondaryAction": "Commercial contact",
	"home.intro.eyebrow": "Origin and purpose",
	"home.intro.title": "A value chain rooted in its territory",
	"home.intro.body": "Conservation, community management and quality — for buyers who value a responsible origin.",
	"home.values.1.title": "Clear origin",
	"home.values.1.body": "Fiber connected to producing communities and territories.",
	"home.values.2.title": "Responsible management",
	"home.values.2.body": "Harvesting that supports the conservation of wild vicuña.",
	"home.values.3.title": "Direct relationship, community origin",
	"home.values.3.body": "A commercial process built on conversation and clear agreements.",
	"home.feature.eyebrow": "Vicuña fiber",
	"home.feature.title": "Natural quality, high-Andean identity",
	"home.feature.body": "An exceptional raw material for specialized buyers and high-value textile supply chains.",
	"home.feature.action": "View characteristics",
	"home.closing.title": "Let's discuss availability and commercial opportunities.",
	"home.closing.body": "Every operation begins with a direct conversation with ANMVB.",
	"home.closing.action": "Start a conversation",
	"fiber.pageTitle": "Vicuña Fiber",
	"fiber.hero.eyebrow": "Vicuña fiber",
	"fiber.hero.title": "An exceptional fiber, from its origin",
	"fiber.hero.body": "Quality, origin and availability of vicuña fiber — what you need to know before getting in touch.",
	"fiber.material.eyebrow": "Raw material",
	"fiber.material.title": "What makes it unique",
	"fiber.material.body": "Vicuña fiber stands out for its fineness, lightness and softness, along with a warmth and hand-feel rarely found in other natural fibers. These properties are why it has long been considered one of the most sought-after fibers in the world.",
	"fiber.heritage.eyebrow": "Andean heritage",
	"fiber.heritage.title": "A practice with old roots",
	"fiber.heritage.body": "Herding, capturing and shearing vicuña isn't new — pre-Hispanic Andean cultures already practiced it, centuries ago. The sustainable management system Bolivian communities follow today is just over 25 years old, but it draws on that inherited knowledge.",
	"fiber.origin.eyebrow": "Provenance",
	"fiber.origin.title": "Origin and traceability",
	"fiber.origin.body": "The fiber comes from vicuñas managed by Bolivian communities. In every transaction, we aim to keep that connection clear — between the product, the community behind it, and the territory it comes from.",
	"fiber.sales.eyebrow": "Commercial process",
	"fiber.sales.title": "Availability and sales process",
	"fiber.sales.body": "Available volumes depend on each season's production. ANMVB handles every inquiry directly, to discuss availability, price, documentation, delivery and other commercial terms.",
	"fiber.closing.title": "Ask about available fiber",
	"fiber.closing.body": "If you're looking for vicuña fiber backed by verified origin, get in touch and we'll walk you through what's currently available.",
	"fiber.closing.action": "Contact ANMVB",
	"organization.pageTitle": "Association",
	"organization.hero.eyebrow": "The association",
	"organization.hero.title": "Communities organized around vicuña",
	"organization.hero.body": "National representation to strengthen management, conservation and fiber commercialization.",
	"organization.identity.eyebrow": "Identity",
	"organization.identity.title": "Who we are",
	"organization.identity.body": "ANMVB brings together the communities and organizations involved in vicuña management across Bolivia. The association represents their interests and strengthens their role in the fiber value chain.",
	"organization.purpose.eyebrow": "Direction",
	"organization.purpose.title": "Our purpose",
	"organization.purpose.body": "We work to ensure that responsible vicuña management opens up better opportunities for communities, through coordination, representation and an organized commercial process.",
	"organization.conservation.eyebrow": "Commitment",
	"organization.conservation.title": "Management and conservation",
	"organization.conservation.body": "Community management ties the use of vicuña fiber to the care of the species and its habitat. Conservation is what sustains this activity — and its value for communities — over time.",
	"organization.closing.title": "Meet an organization rooted in communities",
	"organization.closing.body": "ANMVB combines territorial experience with commercial vision.",
	"organization.closing.action": "Talk to the association",
	"contact.pageTitle": "Commercial Contact",
	"contact.hero.eyebrow": "Commercial contact",
	"contact.hero.title": "Let's discuss Bolivian vicuña fiber",
	"contact.hero.body": "We work with buyers who want to learn more about the availability, volumes and commercial terms of the fiber supplied by our member communities.",
	"contact.hero.action": "Make an inquiry",
	"contact.hero.imageAlt": "Grouped Bolivian vicuña fiber",
	"contact.requirements.eyebrow": "What we need to know",
	"contact.requirements.title": "Tell us what you are looking for",
	"contact.requirements.body": "To give you a concrete answer, tell us what kind of buyer or company you are, what you'll use the fiber for, the approximate volume you need and the destination country.",
	"contact.requirements.1": "Buyer",
	"contact.requirements.2": "Use",
	"contact.requirements.3": "Volume",
	"contact.requirements.4": "Destination",
	"contact.availability.eyebrow": "Availability",
	"contact.availability.title": "Supply according to season and production",
	"contact.availability.body": "ANMVB brings together the fiber supplied by its member communities. Availability and volumes vary by season, so we review each request against the production available at the time.",
	"contact.availability.imageAlt": "Person working with vicuña fiber",
	"contact.process.eyebrow": "How a purchase is arranged",
	"contact.process.1.title": "Inquiry",
	"contact.process.1.body": "You tell us what you're looking for and the details of the purchase.",
	"contact.process.2.title": "Proposal",
	"contact.process.2.body": "We confirm availability and discuss volume, price and applicable terms.",
	"contact.process.3.title": "Agreement",
	"contact.process.3.body": "Together, we work out documentation, delivery and the remaining commercial terms.",
	"contact.closing.title": "A direct commercial relationship with the communities that manage vicuña",
	"contact.closing.body": "If you're looking for vicuña fiber of Bolivian origin, get in touch. We can talk through your requirements and what's currently available.",
	"contact.closing.action": "Contact ANMVB",
	"contact.closing.imageAlt": "Vicuñas with their community handlers",
} as const satisfies Record<keyof typeof es, string>

export const translations = { es, en } as const

export type ContentPage = Exclude<RouteName, "home">
