services:
  postgres:
    image: postgres:16
    container_name: vicugna-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vicugna
      POSTGRES_PASSWORD: vicugna
      POSTGRES_DB: vicugna
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
